resources:
  - name: docker-repo
    type: git
    source:
      uri: {{git_repo_url}}
      branch: master
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: docker_image
    type: docker-image
    source:
      repository: {{container_fullname}}
      email: {{docker_mail}}
      aws_access_key_id: {{aws_access_key_id}}
      aws_secret_access_key: {{aws_secret_access_key}}
      cache: true

  - name: resource_version
    type: semver
    source:
      driver: git
      initial_version: 0.0.1
      uri: {{git_repo_url}}
      branch: version
      file: version
      private_key: {{git_private_key}}
      username: {{github_user}}

jobs:
  - name: docker-release
    serial: true
    plan:
      - get: docker-repo
        trigger: true
      - put: resource_version
        params: {bump: patch}
      - put: docker_image
        params:
          build: docker-repo
          tag: resource_version/version
          tag_as_latest: true